#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);
my $event = 'nethserver-tancredi-update';

event_templates($event, qw(
    /etc/tancredi.conf
    /etc/httpd/conf.d/tancredi.conf
    /etc/opt/rh/rh-php56/php-fpm.d/tancredi.conf
));

event_actions($event, qw(
    initialize-default-databases 00
    nethserver-tancredi-conf 60
));

event_services($event ,qw(
    httpd reload
    rh-php56-php-fpm restart
));

# expand tancredi httpd template on nethserver-freepbx-httpd-save
event_templates("nethserver-freepbx-httpd-save", qw(
    /etc/httpd/conf.d/tancredi.conf
));

#
# trusted-networks-modify event
#

$event = "trusted-networks-modify";

event_templates($event, qw(
    /etc/httpd/conf.d/tancredi.conf
));

event_services($event, qw(
    httpd reload
));

#
# nethserver-php-update event -- catch timezone changes
#
event_templates('nethserver-php-update', qw(
    /etc/opt/rh/rh-php56/php-fpm.d/tancredi.conf
));

event_services('nethserver-php-update', qw(
    rh-php56-php-fpm reload
));

