#!/bin/bash

#
# Copyright (C) 2020 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

function migrate {
    LK=$(/sbin/e-smith/config getprop subscription SystemId)
    SECRET=$(/usr/bin/sudo /sbin/e-smith/config getprop subscription Secret)
    runuser -s /bin/bash -c "/usr/bin/scl enable rh-php56 -- php /usr/share/tancredi/scripts/migration.php $LK $SECRET" - apache
}

ENGINE=$(/sbin/e-smith/config getprop nethvoice ProvisioningEngine)

if [[ $ENGINE != 'tancredi' ]] ; then
    /sbin/e-smith/config setprop nethvoice ProvisioningEngine tancredi
    migrate
    /sbin/e-smith/signal-event nethserver-dnsmasq-update
    echo "[NOTICE] Migration completed. The provisioning service is now Tancredi."
elif [[ $1 == '-f' ]] ; then
    echo "[NOTICE] Discarding any existing data in Tancredi database"
    find /var/lib/tancredi/data/{scopes,first_access_tokens,tokens} -type f -delete
    migrate
    /sbin/e-smith/signal-event nethserver-dnsmasq-update
    echo "[NOTICE] Migration completed in force (-f) mode. The provisioning service is still Tancredi."
elif [[ $1 == '-d' ]] ; then
    find /var/lib/tancredi/data/{scopes,first_access_tokens,tokens} -type f -delete
    /sbin/e-smith/config setprop nethvoice ProvisioningEngine freepbx
    /sbin/e-smith/signal-event nethserver-dnsmasq-update
    echo "[NOTICE] The provisioning engine is now FreePBX End Point Manager."
elif [[ $1 == '-h' ]] ; then
    echo "Usage: $0 [OPTION]"
    echo -e "Migrate provisioning engine and configured devices to Tancredi\n"
    echo -e "With no option, migration is launched only once\n"
    echo -e "-f\t force migration even if tancredi is already the provisioning engine"
    echo -e "-d\t restore freepbx provisioning engine End Point Manager"
else
    echo "[NOTICE] Provisionong engine is already Tancredi. Nothing to do."
    exit 0
fi
