#!/bin/bash

root_db_pwd=$(perl -e "use NethServer::Password; print NethServer::Password::store('mysql')")
db_pwd=$(perl -e "use NethServer::Password; print NethServer::Password::store('TancrediDBPass')")

mysql -u root -p$root_db_pwd <<EOF
USE mysql;

GRANT SELECT on asterisk.ampusers TO 'tancredi'@'localhost' identified by '$db_pwd';

FLUSH privileges;
EOF

# set default.ini on first install
dst_file="/var/lib/tancredi/data/scopes/defaults.ini"

if [[ ! -f ${dst_file} ]]; then
    echo "NOTICE: $0 initializing ${dst_file}"
    /bin/cp -v /usr/share/tancredi/data/scopes/defaults.ini ${dst_file}

    # Add variable for UI first configuration
    echo 'ui_first_config = "1"' >> ${dst_file}

    # Remove variables if they exists
    for variable in timezone language tonezone hostname provisioning_url_scheme time_format date_format ldap_server ldap_port ldap_tls ldap_user ldap_password ldap_base ldap_name_display ldap_number_attr ldap_mainphone_number_attr ldap_mobilephone_number_attr ldap_otherphone_number_attr ldap_name_attr ldap_number_filter ldap_name_filter adminpw userpw; do
        sed -i '/^'${variable}' =.*/d' ${dst_file}
    done

    # Add defaults
    echo 'timezone = "Europe/Rome"' >> ${dst_file}
    echo 'language = "it"' >> ${dst_file}
    echo 'tonezone = "it"' >> ${dst_file}
    echo 'hostname = "'$(hostname)'"' >> ${dst_file}
    echo 'provisioning_url_scheme = "https"' >> ${dst_file}

    # set ldap defaults
    echo 'ldap_server = "'$(hostname)'"' >> ${dst_file}
    echo 'ldap_port = "10389"' >> ${dst_file}
    echo 'ldap_tls = "none"' >> ${dst_file}
    echo 'ldap_user = ""' >> ${dst_file}
    echo 'ldap_password = ""' >> ${dst_file}
    echo 'ldap_base = ""' >> ${dst_file}
    echo 'ldap_name_display = "%cn %o"' >> ${dst_file}
    echo 'ldap_number_attr = "telephoneNumber mobile homePhone"' >> ${dst_file}
    echo 'ldap_mainphone_number_attr = ""' >> ${dst_file}
    echo 'ldap_mobilephone_number_attr = ""' >> ${dst_file}
    echo 'ldap_otherphone_number_attr = ""' >> ${dst_file}
    echo 'ldap_name_attr = "cn o"' >> ${dst_file}
    echo 'ldap_number_filter = "(|(telephoneNumber=%)(mobile=%)(homePhone=%))"' >> ${dst_file}
    echo 'ldap_name_filter = "(|(cn=%)(o=%))"' >> ${dst_file}

    # Set default admin and user passwords
    echo 'adminpw = "'$(head /dev/urandom | tr -dc a-z0-9 | head -c 10)'"' >> ${dst_file}
    echo 'userpw = "'$(head /dev/urandom | tr -dc a-z | head -c 6)'"' >> ${dst_file}
fi

