#!/bin/bash

root_db_pwd=$(perl -e "use NethServer::Password; print NethServer::Password::store('mysql')")
db_pwd=$(perl -e "use NethServer::Password; print NethServer::Password::store('TancrediDBPass')")

mysql -u root -p$root_db_pwd <<EOF
USE mysql;

GRANT SELECT on asterisk.ampusers TO 'tancredi'@'localhost' identified by '$db_pwd';

FLUSH privileges;
EOF

# Set language and tonezone using timezone
function setVars () {
    if [[ $1 == "Europe/Rome" ]]; then
        LANGUAGE="it"
        TONEZONE="it"
    fi
}

# set default.ini on first install
if [[ ! -f /var/lib/tancredi/data/scopes/defaults.ini ]]; then
    cp /usr/share/tancredi/data/scopes/defaults.ini /var/lib/tancredi/data/scopes/defaults.ini

    # Add variable for UI first configuration
    echo 'ui_first_config = "1"' >> /var/lib/tancredi/data/scopes/defaults.ini

    # Remove timezone, language and tonezone if they exists
    sed -i '/^timezone = /d' /var/lib/tancredi/data/scopes/defaults.ini
    sed -i '/^language = /d' /var/lib/tancredi/data/scopes/defaults.ini
    sed -i '/^tonezone = /d' /var/lib/tancredi/data/scopes/defaults.ini

    # Add timezone, hardcoded to Eurpe/Rome
    TIMEZONE="Europe/Rome"
    echo 'timezone = "'${TIMEZONE}'"' >> /var/lib/tancredi/data/scopes/defaults.ini

    # Add default language and tonezone based on timezone
    LANGUAGE="en"
    TONEZONE="us"
    setVars $TIMEZONE
    echo 'language = "'${LANGUAGE}'"' >> /var/lib/tancredi/data/scopes/defaults.ini
    echo 'tonezone = "'${TONEZONE}'"' >> /var/lib/tancredi/data/scopes/defaults.ini
fi

